// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: ItemSummary.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conv *ItemSummary_Conversation `protobuf:"bytes,1,opt,name=conv,proto3" json:"conv,omitempty"`
	Msgs []*ItemSummary_Message    `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *ItemSummary) Reset() {
	*x = ItemSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemSummary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSummary) ProtoMessage() {}

func (x *ItemSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ItemSummary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSummary.ProtoReflect.Descriptor instead.
func (*ItemSummary) Descriptor() ([]byte, []int) {
	return file_ItemSummary_proto_rawDescGZIP(), []int{0}
}

func (x *ItemSummary) GetConv() *ItemSummary_Conversation {
	if x != nil {
		return x.Conv
	}
	return nil
}

func (x *ItemSummary) GetMsgs() []*ItemSummary_Message {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type ItemSummary_Conversation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerPermId  string `protobuf:"bytes,1,opt,name=server_perm_id,json=serverPermId,proto3" json:"server_perm_id,omitempty"`
	Subject       string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Snippet       string `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Epoch         uint64 `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	UnknownBool   uint32 `protobuf:"varint,13,opt,name=unknown_bool,json=unknownBool,proto3" json:"unknown_bool,omitempty"`
	UnknownBool_2 uint64 `protobuf:"fixed64,14,opt,name=unknown_bool_2,json=unknownBool2,proto3" json:"unknown_bool_2,omitempty"`
}

func (x *ItemSummary_Conversation) Reset() {
	*x = ItemSummary_Conversation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemSummary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemSummary_Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSummary_Conversation) ProtoMessage() {}

func (x *ItemSummary_Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_ItemSummary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSummary_Conversation.ProtoReflect.Descriptor instead.
func (*ItemSummary_Conversation) Descriptor() ([]byte, []int) {
	return file_ItemSummary_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ItemSummary_Conversation) GetServerPermId() string {
	if x != nil {
		return x.ServerPermId
	}
	return ""
}

func (x *ItemSummary_Conversation) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ItemSummary_Conversation) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *ItemSummary_Conversation) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ItemSummary_Conversation) GetUnknownBool() uint32 {
	if x != nil {
		return x.UnknownBool
	}
	return 0
}

func (x *ItemSummary_Conversation) GetUnknownBool_2() uint64 {
	if x != nil {
		return x.UnknownBool_2
	}
	return 0
}

type ItemSummary_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerPermId   string                     `protobuf:"bytes,1,opt,name=server_perm_id,json=serverPermId,proto3" json:"server_perm_id,omitempty"`
	Emails         *ItemSummary_Email         `protobuf:"bytes,2,opt,name=emails,proto3" json:"emails,omitempty"`
	Epoch          uint64                     `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	LabelTypes     []string                   `protobuf:"bytes,4,rep,name=label_types,json=labelTypes,proto3" json:"label_types,omitempty"`
	EpochReceipt_1 uint64                     `protobuf:"fixed64,7,opt,name=epoch_receipt_1,json=epochReceipt1,proto3" json:"epoch_receipt_1,omitempty"`
	MailingList    string                     `protobuf:"bytes,8,opt,name=mailing_list,json=mailingList,proto3" json:"mailing_list,omitempty"`
	UnknownInt     uint64                     `protobuf:"varint,10,opt,name=unknown_int,json=unknownInt,proto3" json:"unknown_int,omitempty"`
	Snippet        string                     `protobuf:"bytes,11,opt,name=snippet,proto3" json:"snippet,omitempty"`
	UnknownEmail   string                     `protobuf:"bytes,12,opt,name=unknown_email,json=unknownEmail,proto3" json:"unknown_email,omitempty"`
	EpochReceipt_2 uint64                     `protobuf:"varint,16,opt,name=epoch_receipt_2,json=epochReceipt2,proto3" json:"epoch_receipt_2,omitempty"`
	IntMsg         uint32                     `protobuf:"varint,17,opt,name=int_msg,json=intMsg,proto3" json:"int_msg,omitempty"`
	BoolMsg        uint32                     `protobuf:"varint,22,opt,name=bool_msg,json=boolMsg,proto3" json:"bool_msg,omitempty"`
	TwentyFour     *ItemSummary_TwentyFourKey `protobuf:"bytes,24,opt,name=twenty_four,json=twentyFour,proto3" json:"twenty_four,omitempty"`
	Epoch5         uint64                     `protobuf:"varint,25,opt,name=epoch5,proto3" json:"epoch5,omitempty"`
	ThirtyNine     *ItemSummary_ThirtyNine    `protobuf:"bytes,39,opt,name=thirty_nine,json=thirtyNine,proto3" json:"thirty_nine,omitempty"`
}

func (x *ItemSummary_Message) Reset() {
	*x = ItemSummary_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemSummary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemSummary_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSummary_Message) ProtoMessage() {}

func (x *ItemSummary_Message) ProtoReflect() protoreflect.Message {
	mi := &file_ItemSummary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSummary_Message.ProtoReflect.Descriptor instead.
func (*ItemSummary_Message) Descriptor() ([]byte, []int) {
	return file_ItemSummary_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ItemSummary_Message) GetServerPermId() string {
	if x != nil {
		return x.ServerPermId
	}
	return ""
}

func (x *ItemSummary_Message) GetEmails() *ItemSummary_Email {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *ItemSummary_Message) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ItemSummary_Message) GetLabelTypes() []string {
	if x != nil {
		return x.LabelTypes
	}
	return nil
}

func (x *ItemSummary_Message) GetEpochReceipt_1() uint64 {
	if x != nil {
		return x.EpochReceipt_1
	}
	return 0
}

func (x *ItemSummary_Message) GetMailingList() string {
	if x != nil {
		return x.MailingList
	}
	return ""
}

func (x *ItemSummary_Message) GetUnknownInt() uint64 {
	if x != nil {
		return x.UnknownInt
	}
	return 0
}

func (x *ItemSummary_Message) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *ItemSummary_Message) GetUnknownEmail() string {
	if x != nil {
		return x.UnknownEmail
	}
	return ""
}

func (x *ItemSummary_Message) GetEpochReceipt_2() uint64 {
	if x != nil {
		return x.EpochReceipt_2
	}
	return 0
}

func (x *ItemSummary_Message) GetIntMsg() uint32 {
	if x != nil {
		return x.IntMsg
	}
	return 0
}

func (x *ItemSummary_Message) GetBoolMsg() uint32 {
	if x != nil {
		return x.BoolMsg
	}
	return 0
}

func (x *ItemSummary_Message) GetTwentyFour() *ItemSummary_TwentyFourKey {
	if x != nil {
		return x.TwentyFour
	}
	return nil
}

func (x *ItemSummary_Message) GetEpoch5() uint64 {
	if x != nil {
		return x.Epoch5
	}
	return 0
}

func (x *ItemSummary_Message) GetThirtyNine() *ItemSummary_ThirtyNine {
	if x != nil {
		return x.ThirtyNine
	}
	return nil
}

type ItemSummary_Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ItemSummary_Email) Reset() {
	*x = ItemSummary_Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemSummary_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemSummary_Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSummary_Email) ProtoMessage() {}

func (x *ItemSummary_Email) ProtoReflect() protoreflect.Message {
	mi := &file_ItemSummary_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSummary_Email.ProtoReflect.Descriptor instead.
func (*ItemSummary_Email) Descriptor() ([]byte, []int) {
	return file_ItemSummary_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ItemSummary_Email) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemSummary_Email) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ItemSummary_Email) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ItemSummary_TwentyFourKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BooleanValue uint32 `protobuf:"varint,3,opt,name=boolean_value,json=booleanValue,proto3" json:"boolean_value,omitempty"`
	Email        string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ItemSummary_TwentyFourKey) Reset() {
	*x = ItemSummary_TwentyFourKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemSummary_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemSummary_TwentyFourKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSummary_TwentyFourKey) ProtoMessage() {}

func (x *ItemSummary_TwentyFourKey) ProtoReflect() protoreflect.Message {
	mi := &file_ItemSummary_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSummary_TwentyFourKey.ProtoReflect.Descriptor instead.
func (*ItemSummary_TwentyFourKey) Descriptor() ([]byte, []int) {
	return file_ItemSummary_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ItemSummary_TwentyFourKey) GetBooleanValue() uint32 {
	if x != nil {
		return x.BooleanValue
	}
	return 0
}

func (x *ItemSummary_TwentyFourKey) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ItemSummary_ThirtyNine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IntegerValue uint32 `protobuf:"varint,4,opt,name=integer_value,json=integerValue,proto3" json:"integer_value,omitempty"`
}

func (x *ItemSummary_ThirtyNine) Reset() {
	*x = ItemSummary_ThirtyNine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemSummary_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemSummary_ThirtyNine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSummary_ThirtyNine) ProtoMessage() {}

func (x *ItemSummary_ThirtyNine) ProtoReflect() protoreflect.Message {
	mi := &file_ItemSummary_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSummary_ThirtyNine.ProtoReflect.Descriptor instead.
func (*ItemSummary_ThirtyNine) Descriptor() ([]byte, []int) {
	return file_ItemSummary_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ItemSummary_ThirtyNine) GetIntegerValue() uint32 {
	if x != nil {
		return x.IntegerValue
	}
	return 0
}

var File_ItemSummary_proto protoreflect.FileDescriptor

var file_ItemSummary_proto_rawDesc = []byte{
	0x0a, 0x11, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x08, 0x0a, 0x0b, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x12, 0x2d, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e,
	0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x6f,
	0x6e, 0x76, 0x12, 0x28, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0xc7, 0x01, 0x0a,
	0x0c, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a,
	0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x65, 0x72,
	0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x21, 0x0a,
	0x0c, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x42, 0x6f, 0x6f, 0x6c,
	0x12, 0x24, 0x0a, 0x0e, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x62, 0x6f, 0x6f, 0x6c,
	0x5f, 0x32, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x06, 0x52, 0x0c, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x42, 0x6f, 0x6f, 0x6c, 0x32, 0x1a, 0xa8, 0x04, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x65, 0x72,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x50, 0x65, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x65,
	0x70, 0x6f, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x5f, 0x31, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x06, 0x52, 0x0d, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x31, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x69, 0x6c, 0x69,
	0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x75, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6e, 0x69, 0x70, 0x70,
	0x65, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65,
	0x74, 0x12, 0x23, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x5f,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x5f, 0x32, 0x18, 0x10, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0d, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x32, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x69, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6c, 0x5f,
	0x6d, 0x73, 0x67, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x4d,
	0x73, 0x67, 0x12, 0x3b, 0x0a, 0x0b, 0x74, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x5f, 0x66, 0x6f, 0x75,
	0x72, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x54, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x46, 0x6f, 0x75, 0x72,
	0x4b, 0x65, 0x79, 0x52, 0x0a, 0x74, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x46, 0x6f, 0x75, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x35, 0x18, 0x19, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x35, 0x12, 0x38, 0x0a, 0x0b, 0x74, 0x68, 0x69, 0x72, 0x74,
	0x79, 0x5f, 0x6e, 0x69, 0x6e, 0x65, 0x18, 0x27, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x74,
	0x79, 0x4e, 0x69, 0x6e, 0x65, 0x52, 0x0a, 0x74, 0x68, 0x69, 0x72, 0x74, 0x79, 0x4e, 0x69, 0x6e,
	0x65, 0x1a, 0x45, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x4a, 0x0a, 0x0d, 0x54, 0x77, 0x65, 0x6e,
	0x74, 0x79, 0x46, 0x6f, 0x75, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x6f, 0x6f,
	0x6c, 0x65, 0x61, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x31, 0x0a, 0x0a, 0x54, 0x68, 0x69, 0x72, 0x74, 0x79, 0x4e, 0x69,
	0x6e, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ItemSummary_proto_rawDescOnce sync.Once
	file_ItemSummary_proto_rawDescData = file_ItemSummary_proto_rawDesc
)

func file_ItemSummary_proto_rawDescGZIP() []byte {
	file_ItemSummary_proto_rawDescOnce.Do(func() {
		file_ItemSummary_proto_rawDescData = protoimpl.X.CompressGZIP(file_ItemSummary_proto_rawDescData)
	})
	return file_ItemSummary_proto_rawDescData
}

var file_ItemSummary_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ItemSummary_proto_goTypes = []interface{}{
	(*ItemSummary)(nil),               // 0: ItemSummary
	(*ItemSummary_Conversation)(nil),  // 1: ItemSummary.Conversation
	(*ItemSummary_Message)(nil),       // 2: ItemSummary.Message
	(*ItemSummary_Email)(nil),         // 3: ItemSummary.Email
	(*ItemSummary_TwentyFourKey)(nil), // 4: ItemSummary.TwentyFourKey
	(*ItemSummary_ThirtyNine)(nil),    // 5: ItemSummary.ThirtyNine
}
var file_ItemSummary_proto_depIdxs = []int32{
	1, // 0: ItemSummary.conv:type_name -> ItemSummary.Conversation
	2, // 1: ItemSummary.msgs:type_name -> ItemSummary.Message
	3, // 2: ItemSummary.Message.emails:type_name -> ItemSummary.Email
	4, // 3: ItemSummary.Message.twenty_four:type_name -> ItemSummary.TwentyFourKey
	5, // 4: ItemSummary.Message.thirty_nine:type_name -> ItemSummary.ThirtyNine
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ItemSummary_proto_init() }
func file_ItemSummary_proto_init() {
	if File_ItemSummary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ItemSummary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ItemSummary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemSummary_Conversation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ItemSummary_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemSummary_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ItemSummary_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemSummary_Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ItemSummary_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemSummary_TwentyFourKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ItemSummary_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemSummary_ThirtyNine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ItemSummary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ItemSummary_proto_goTypes,
		DependencyIndexes: file_ItemSummary_proto_depIdxs,
		MessageInfos:      file_ItemSummary_proto_msgTypes,
	}.Build()
	File_ItemSummary_proto = out.File
	file_ItemSummary_proto_rawDesc = nil
	file_ItemSummary_proto_goTypes = nil
	file_ItemSummary_proto_depIdxs = nil
}
