// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: Message.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver               []*Message_Email         `protobuf:"bytes,1,rep,name=receiver,proto3" json:"receiver,omitempty"`
	Cc                     []*Message_Email         `protobuf:"bytes,2,rep,name=cc,proto3" json:"cc,omitempty"`
	Sender                 *Message_Email           `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Subject                string                   `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Html                   *Message_Html            `protobuf:"bytes,6,opt,name=html,proto3" json:"html,omitempty"`
	Snippet                string                   `protobuf:"bytes,7,opt,name=snippet,proto3" json:"snippet,omitempty"`
	InternalMailProvider_1 string                   `protobuf:"bytes,8,opt,name=internal_mail_provider_1,json=internalMailProvider1,proto3" json:"internal_mail_provider_1,omitempty"`
	InternalMailProvider_2 string                   `protobuf:"bytes,9,opt,name=internal_mail_provider_2,json=internalMailProvider2,proto3" json:"internal_mail_provider_2,omitempty"`
	InternalMailProvider_3 string                   `protobuf:"bytes,10,opt,name=internal_mail_provider_3,json=internalMailProvider3,proto3" json:"internal_mail_provider_3,omitempty"`
	SenderSecondary        *Message_SenderSecondary `protobuf:"bytes,11,opt,name=sender_secondary,json=senderSecondary,proto3" json:"sender_secondary,omitempty"`
	ReceiverSecondary      *Message_Email           `protobuf:"bytes,12,opt,name=receiver_secondary,json=receiverSecondary,proto3" json:"receiver_secondary,omitempty"`
	Attachments            []*Message_Attachment    `protobuf:"bytes,14,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Epoch                  uint64                   `protobuf:"varint,17,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Tw                     *Message_TwentyKey       `protobuf:"bytes,20,opt,name=tw,proto3" json:"tw,omitempty"`
	TwOne                  *Message_TwentyOneKey    `protobuf:"bytes,21,opt,name=tw_one,json=twOne,proto3" json:"tw_one,omitempty"`
	InternalId             uint64                   `protobuf:"varint,29,opt,name=internal_id,json=internalId,proto3" json:"internal_id,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetReceiver() []*Message_Email {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *Message) GetCc() []*Message_Email {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *Message) GetSender() *Message_Email {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *Message) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Message) GetHtml() *Message_Html {
	if x != nil {
		return x.Html
	}
	return nil
}

func (x *Message) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Message) GetInternalMailProvider_1() string {
	if x != nil {
		return x.InternalMailProvider_1
	}
	return ""
}

func (x *Message) GetInternalMailProvider_2() string {
	if x != nil {
		return x.InternalMailProvider_2
	}
	return ""
}

func (x *Message) GetInternalMailProvider_3() string {
	if x != nil {
		return x.InternalMailProvider_3
	}
	return ""
}

func (x *Message) GetSenderSecondary() *Message_SenderSecondary {
	if x != nil {
		return x.SenderSecondary
	}
	return nil
}

func (x *Message) GetReceiverSecondary() *Message_Email {
	if x != nil {
		return x.ReceiverSecondary
	}
	return nil
}

func (x *Message) GetAttachments() []*Message_Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *Message) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Message) GetTw() *Message_TwentyKey {
	if x != nil {
		return x.Tw
	}
	return nil
}

func (x *Message) GetTwOne() *Message_TwentyOneKey {
	if x != nil {
		return x.TwOne
	}
	return nil
}

func (x *Message) GetInternalId() uint64 {
	if x != nil {
		return x.InternalId
	}
	return 0
}

type Message_Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Message_Email) Reset() {
	*x = Message_Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Email) ProtoMessage() {}

func (x *Message_Email) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Email.ProtoReflect.Descriptor instead.
func (*Message_Email) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Email) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message_Email) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Message_Email) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message_Html struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HtmlDetails     *Message_HtmlDetails `protobuf:"bytes,2,opt,name=html_details,json=htmlDetails,proto3" json:"html_details,omitempty"`
	UnknownInt      uint32               `protobuf:"varint,3,opt,name=unknown_int,json=unknownInt,proto3" json:"unknown_int,omitempty"`
	UrlMsg          string               `protobuf:"bytes,4,opt,name=url_msg,json=urlMsg,proto3" json:"url_msg,omitempty"`
	Css             *Message_CSS         `protobuf:"bytes,5,opt,name=css,proto3" json:"css,omitempty"`
	MsgServerPermId string               `protobuf:"bytes,6,opt,name=msg_server_perm_id,json=msgServerPermId,proto3" json:"msg_server_perm_id,omitempty"`
	UnknownInt_2    uint32               `protobuf:"varint,7,opt,name=unknown_int_2,json=unknownInt2,proto3" json:"unknown_int_2,omitempty"`
	UnknownInt_3    uint32               `protobuf:"varint,8,opt,name=unknown_int_3,json=unknownInt3,proto3" json:"unknown_int_3,omitempty"`
}

func (x *Message_Html) Reset() {
	*x = Message_Html{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_Html) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Html) ProtoMessage() {}

func (x *Message_Html) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Html.ProtoReflect.Descriptor instead.
func (*Message_Html) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Message_Html) GetHtmlDetails() *Message_HtmlDetails {
	if x != nil {
		return x.HtmlDetails
	}
	return nil
}

func (x *Message_Html) GetUnknownInt() uint32 {
	if x != nil {
		return x.UnknownInt
	}
	return 0
}

func (x *Message_Html) GetUrlMsg() string {
	if x != nil {
		return x.UrlMsg
	}
	return ""
}

func (x *Message_Html) GetCss() *Message_CSS {
	if x != nil {
		return x.Css
	}
	return nil
}

func (x *Message_Html) GetMsgServerPermId() string {
	if x != nil {
		return x.MsgServerPermId
	}
	return ""
}

func (x *Message_Html) GetUnknownInt_2() uint32 {
	if x != nil {
		return x.UnknownInt_2
	}
	return 0
}

func (x *Message_Html) GetUnknownInt_3() uint32 {
	if x != nil {
		return x.UnknownInt_3
	}
	return 0
}

type Message_HtmlDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnknownId_1 uint32           `protobuf:"varint,1,opt,name=unknown_id_1,json=unknownId1,proto3" json:"unknown_id_1,omitempty"`
	Body        *Message_RawHTML `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	UnknownId_2 uint32           `protobuf:"varint,4,opt,name=unknown_id_2,json=unknownId2,proto3" json:"unknown_id_2,omitempty"`
}

func (x *Message_HtmlDetails) Reset() {
	*x = Message_HtmlDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_HtmlDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_HtmlDetails) ProtoMessage() {}

func (x *Message_HtmlDetails) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_HtmlDetails.ProtoReflect.Descriptor instead.
func (*Message_HtmlDetails) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Message_HtmlDetails) GetUnknownId_1() uint32 {
	if x != nil {
		return x.UnknownId_1
	}
	return 0
}

func (x *Message_HtmlDetails) GetBody() *Message_RawHTML {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message_HtmlDetails) GetUnknownId_2() uint32 {
	if x != nil {
		return x.UnknownId_2
	}
	return 0
}

type Message_RawHTML struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message_RawHTML) Reset() {
	*x = Message_RawHTML{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_RawHTML) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_RawHTML) ProtoMessage() {}

func (x *Message_RawHTML) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_RawHTML.ProtoReflect.Descriptor instead.
func (*Message_RawHTML) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Message_RawHTML) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type Message_CSS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Css string `protobuf:"bytes,7,opt,name=css,proto3" json:"css,omitempty"`
}

func (x *Message_CSS) Reset() {
	*x = Message_CSS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_CSS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_CSS) ProtoMessage() {}

func (x *Message_CSS) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_CSS.ProtoReflect.Descriptor instead.
func (*Message_CSS) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Message_CSS) GetCss() string {
	if x != nil {
		return x.Css
	}
	return ""
}

type Message_SenderSecondary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnknownInt_1        uint32           `protobuf:"varint,1,opt,name=unknown_int_1,json=unknownInt1,proto3" json:"unknown_int_1,omitempty"`
	UnknownInt_2        uint32           `protobuf:"varint,2,opt,name=unknown_int_2,json=unknownInt2,proto3" json:"unknown_int_2,omitempty"`
	Sender_3            *MessageSender_3 `protobuf:"bytes,3,opt,name=sender_3,json=sender3,proto3" json:"sender_3,omitempty"`
	UnknownId           uint64           `protobuf:"varint,4,opt,name=unknown_id,json=unknownId,proto3" json:"unknown_id,omitempty"`
	Domain              string           `protobuf:"bytes,8,opt,name=domain,proto3" json:"domain,omitempty"`
	InternalDomain      string           `protobuf:"bytes,9,opt,name=internal_domain,json=internalDomain,proto3" json:"internal_domain,omitempty"`
	UnknownInt_3        uint32           `protobuf:"varint,11,opt,name=unknown_int_3,json=unknownInt3,proto3" json:"unknown_int_3,omitempty"`
	UnknownInt_4        uint32           `protobuf:"varint,12,opt,name=unknown_int_4,json=unknownInt4,proto3" json:"unknown_int_4,omitempty"`
	UnknownInt_5        uint32           `protobuf:"varint,13,opt,name=unknown_int_5,json=unknownInt5,proto3" json:"unknown_int_5,omitempty"`
	InternalUrlProvider string           `protobuf:"bytes,14,opt,name=internal_url_provider,json=internalUrlProvider,proto3" json:"internal_url_provider,omitempty"`
	AccountName         string           `protobuf:"bytes,15,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Email               string           `protobuf:"bytes,17,opt,name=email,proto3" json:"email,omitempty"`
	UnknownInt_6        uint32           `protobuf:"varint,18,opt,name=unknown_int_6,json=unknownInt6,proto3" json:"unknown_int_6,omitempty"`
}

func (x *Message_SenderSecondary) Reset() {
	*x = Message_SenderSecondary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_SenderSecondary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_SenderSecondary) ProtoMessage() {}

func (x *Message_SenderSecondary) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_SenderSecondary.ProtoReflect.Descriptor instead.
func (*Message_SenderSecondary) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Message_SenderSecondary) GetUnknownInt_1() uint32 {
	if x != nil {
		return x.UnknownInt_1
	}
	return 0
}

func (x *Message_SenderSecondary) GetUnknownInt_2() uint32 {
	if x != nil {
		return x.UnknownInt_2
	}
	return 0
}

func (x *Message_SenderSecondary) GetSender_3() *MessageSender_3 {
	if x != nil {
		return x.Sender_3
	}
	return nil
}

func (x *Message_SenderSecondary) GetUnknownId() uint64 {
	if x != nil {
		return x.UnknownId
	}
	return 0
}

func (x *Message_SenderSecondary) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Message_SenderSecondary) GetInternalDomain() string {
	if x != nil {
		return x.InternalDomain
	}
	return ""
}

func (x *Message_SenderSecondary) GetUnknownInt_3() uint32 {
	if x != nil {
		return x.UnknownInt_3
	}
	return 0
}

func (x *Message_SenderSecondary) GetUnknownInt_4() uint32 {
	if x != nil {
		return x.UnknownInt_4
	}
	return 0
}

func (x *Message_SenderSecondary) GetUnknownInt_5() uint32 {
	if x != nil {
		return x.UnknownInt_5
	}
	return 0
}

func (x *Message_SenderSecondary) GetInternalUrlProvider() string {
	if x != nil {
		return x.InternalUrlProvider
	}
	return ""
}

func (x *Message_SenderSecondary) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *Message_SenderSecondary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Message_SenderSecondary) GetUnknownInt_6() uint32 {
	if x != nil {
		return x.UnknownInt_6
	}
	return 0
}

type MessageSender_3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unknown string `protobuf:"bytes,1,opt,name=unknown,proto3" json:"unknown,omitempty"`
}

func (x *MessageSender_3) Reset() {
	*x = MessageSender_3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageSender_3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSender_3) ProtoMessage() {}

func (x *MessageSender_3) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSender_3.ProtoReflect.Descriptor instead.
func (*MessageSender_3) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 6}
}

func (x *MessageSender_3) GetUnknown() string {
	if x != nil {
		return x.Unknown
	}
	return ""
}

type Message_Attachment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InfoAtt      *Message_InfoAttachment          `protobuf:"bytes,1,opt,name=info_att,json=infoAtt,proto3" json:"info_att,omitempty"`
	InternalId   string                           `protobuf:"bytes,3,opt,name=internal_id,json=internalId,proto3" json:"internal_id,omitempty"`
	OtherIntInfo *Message_OtherInternalAttachInfo `protobuf:"bytes,5,opt,name=other_int_info,json=otherIntInfo,proto3" json:"other_int_info,omitempty"`
}

func (x *Message_Attachment) Reset() {
	*x = Message_Attachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Attachment) ProtoMessage() {}

func (x *Message_Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Attachment.ProtoReflect.Descriptor instead.
func (*Message_Attachment) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Message_Attachment) GetInfoAtt() *Message_InfoAttachment {
	if x != nil {
		return x.InfoAtt
	}
	return nil
}

func (x *Message_Attachment) GetInternalId() string {
	if x != nil {
		return x.InternalId
	}
	return ""
}

func (x *Message_Attachment) GetOtherIntInfo() *Message_OtherInternalAttachInfo {
	if x != nil {
		return x.OtherIntInfo
	}
	return nil
}

type Message_InfoAttachment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnknownInt_1  uint32                        `protobuf:"varint,1,opt,name=unknown_int_1,json=unknownInt1,proto3" json:"unknown_int_1,omitempty"`
	UnknownString string                        `protobuf:"bytes,2,opt,name=unknown_string,json=unknownString,proto3" json:"unknown_string,omitempty"`
	UnknownInt_2  uint32                        `protobuf:"varint,3,opt,name=unknown_int_2,json=unknownInt2,proto3" json:"unknown_int_2,omitempty"`
	Attach        *Message_InfoAttachmentDetail `protobuf:"bytes,4,opt,name=attach,proto3" json:"attach,omitempty"`
}

func (x *Message_InfoAttachment) Reset() {
	*x = Message_InfoAttachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_InfoAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_InfoAttachment) ProtoMessage() {}

func (x *Message_InfoAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_InfoAttachment.ProtoReflect.Descriptor instead.
func (*Message_InfoAttachment) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Message_InfoAttachment) GetUnknownInt_1() uint32 {
	if x != nil {
		return x.UnknownInt_1
	}
	return 0
}

func (x *Message_InfoAttachment) GetUnknownString() string {
	if x != nil {
		return x.UnknownString
	}
	return ""
}

func (x *Message_InfoAttachment) GetUnknownInt_2() uint32 {
	if x != nil {
		return x.UnknownInt_2
	}
	return 0
}

func (x *Message_InfoAttachment) GetAttach() *Message_InfoAttachmentDetail {
	if x != nil {
		return x.Attach
	}
	return nil
}

type Message_InfoAttachmentDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnknownInt_1 uint32                                `protobuf:"varint,1,opt,name=unknown_int_1,json=unknownInt1,proto3" json:"unknown_int_1,omitempty"`
	RemoteUrl    string                                `protobuf:"bytes,2,opt,name=remote_url,json=remoteUrl,proto3" json:"remote_url,omitempty"`
	Filename     string                                `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Mimetype     string                                `protobuf:"bytes,4,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Size         uint32                                `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	InternalInfo *Message_InfoInternalAttachmentDetail `protobuf:"bytes,6,opt,name=internal_info,json=internalInfo,proto3" json:"internal_info,omitempty"`
}

func (x *Message_InfoAttachmentDetail) Reset() {
	*x = Message_InfoAttachmentDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_InfoAttachmentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_InfoAttachmentDetail) ProtoMessage() {}

func (x *Message_InfoAttachmentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_InfoAttachmentDetail.ProtoReflect.Descriptor instead.
func (*Message_InfoAttachmentDetail) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Message_InfoAttachmentDetail) GetUnknownInt_1() uint32 {
	if x != nil {
		return x.UnknownInt_1
	}
	return 0
}

func (x *Message_InfoAttachmentDetail) GetRemoteUrl() string {
	if x != nil {
		return x.RemoteUrl
	}
	return ""
}

func (x *Message_InfoAttachmentDetail) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Message_InfoAttachmentDetail) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *Message_InfoAttachmentDetail) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Message_InfoAttachmentDetail) GetInternalInfo() *Message_InfoInternalAttachmentDetail {
	if x != nil {
		return x.InternalInfo
	}
	return nil
}

type Message_InfoInternalAttachmentDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnknownString_1 string `protobuf:"bytes,1,opt,name=unknown_string_1,json=unknownString1,proto3" json:"unknown_string_1,omitempty"`
	UnknownString_2 string `protobuf:"bytes,2,opt,name=unknown_string_2,json=unknownString2,proto3" json:"unknown_string_2,omitempty"`
}

func (x *Message_InfoInternalAttachmentDetail) Reset() {
	*x = Message_InfoInternalAttachmentDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_InfoInternalAttachmentDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_InfoInternalAttachmentDetail) ProtoMessage() {}

func (x *Message_InfoInternalAttachmentDetail) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_InfoInternalAttachmentDetail.ProtoReflect.Descriptor instead.
func (*Message_InfoInternalAttachmentDetail) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Message_InfoInternalAttachmentDetail) GetUnknownString_1() string {
	if x != nil {
		return x.UnknownString_1
	}
	return ""
}

func (x *Message_InfoInternalAttachmentDetail) GetUnknownString_2() string {
	if x != nil {
		return x.UnknownString_2
	}
	return ""
}

type Message_OtherInternalAttachInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InternalRoute string `protobuf:"bytes,1,opt,name=internal_route,json=internalRoute,proto3" json:"internal_route,omitempty"`
	Size          uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	UnknownInt_2  uint32 `protobuf:"varint,3,opt,name=unknown_int_2,json=unknownInt2,proto3" json:"unknown_int_2,omitempty"`
	UnknownInt_3  uint32 `protobuf:"varint,4,opt,name=unknown_int_3,json=unknownInt3,proto3" json:"unknown_int_3,omitempty"`
	UnknownInt_4  uint32 `protobuf:"varint,5,opt,name=unknown_int_4,json=unknownInt4,proto3" json:"unknown_int_4,omitempty"`
	UnknownString string `protobuf:"bytes,6,opt,name=unknown_string,json=unknownString,proto3" json:"unknown_string,omitempty"`
}

func (x *Message_OtherInternalAttachInfo) Reset() {
	*x = Message_OtherInternalAttachInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_OtherInternalAttachInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_OtherInternalAttachInfo) ProtoMessage() {}

func (x *Message_OtherInternalAttachInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_OtherInternalAttachInfo.ProtoReflect.Descriptor instead.
func (*Message_OtherInternalAttachInfo) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 11}
}

func (x *Message_OtherInternalAttachInfo) GetInternalRoute() string {
	if x != nil {
		return x.InternalRoute
	}
	return ""
}

func (x *Message_OtherInternalAttachInfo) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Message_OtherInternalAttachInfo) GetUnknownInt_2() uint32 {
	if x != nil {
		return x.UnknownInt_2
	}
	return 0
}

func (x *Message_OtherInternalAttachInfo) GetUnknownInt_3() uint32 {
	if x != nil {
		return x.UnknownInt_3
	}
	return 0
}

func (x *Message_OtherInternalAttachInfo) GetUnknownInt_4() uint32 {
	if x != nil {
		return x.UnknownInt_4
	}
	return 0
}

func (x *Message_OtherInternalAttachInfo) GetUnknownString() string {
	if x != nil {
		return x.UnknownString
	}
	return ""
}

type Message_TwentyKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Twenty *Message_TwentyKeyNested `protobuf:"bytes,1,opt,name=twenty,proto3" json:"twenty,omitempty"`
}

func (x *Message_TwentyKey) Reset() {
	*x = Message_TwentyKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_TwentyKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_TwentyKey) ProtoMessage() {}

func (x *Message_TwentyKey) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_TwentyKey.ProtoReflect.Descriptor instead.
func (*Message_TwentyKey) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 12}
}

func (x *Message_TwentyKey) GetTwenty() *Message_TwentyKeyNested {
	if x != nil {
		return x.Twenty
	}
	return nil
}

type Message_TwentyKeyNested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TwentyNested string `protobuf:"bytes,2,opt,name=twenty_nested,json=twentyNested,proto3" json:"twenty_nested,omitempty"`
}

func (x *Message_TwentyKeyNested) Reset() {
	*x = Message_TwentyKeyNested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_TwentyKeyNested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_TwentyKeyNested) ProtoMessage() {}

func (x *Message_TwentyKeyNested) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_TwentyKeyNested.ProtoReflect.Descriptor instead.
func (*Message_TwentyKeyNested) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 13}
}

func (x *Message_TwentyKeyNested) GetTwentyNested() string {
	if x != nil {
		return x.TwentyNested
	}
	return ""
}

type Message_TwentyOneKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TwentyOne *MessageTwentyOneNested `protobuf:"bytes,1,opt,name=twenty_one,json=twentyOne,proto3" json:"twenty_one,omitempty"`
}

func (x *Message_TwentyOneKey) Reset() {
	*x = Message_TwentyOneKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message_TwentyOneKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_TwentyOneKey) ProtoMessage() {}

func (x *Message_TwentyOneKey) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_TwentyOneKey.ProtoReflect.Descriptor instead.
func (*Message_TwentyOneKey) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 14}
}

func (x *Message_TwentyOneKey) GetTwentyOne() *MessageTwentyOneNested {
	if x != nil {
		return x.TwentyOne
	}
	return nil
}

type MessageTwentyOneNested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TwentyOneNested string `protobuf:"bytes,2,opt,name=twenty_one_nested,json=twentyOneNested,proto3" json:"twenty_one_nested,omitempty"`
}

func (x *MessageTwentyOneNested) Reset() {
	*x = MessageTwentyOneNested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Message_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageTwentyOneNested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTwentyOneNested) ProtoMessage() {}

func (x *MessageTwentyOneNested) ProtoReflect() protoreflect.Message {
	mi := &file_Message_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTwentyOneNested.ProtoReflect.Descriptor instead.
func (*MessageTwentyOneNested) Descriptor() ([]byte, []int) {
	return file_Message_proto_rawDescGZIP(), []int{0, 15}
}

func (x *MessageTwentyOneNested) GetTwentyOneNested() string {
	if x != nil {
		return x.TwentyOneNested
	}
	return ""
}

var File_Message_proto protoreflect.FileDescriptor

var file_Message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x93, 0x17, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x08, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x02, 0x63, 0x63, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x52, 0x02, 0x63, 0x63, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x21, 0x0a, 0x04, 0x68, 0x74, 0x6d,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x48, 0x74, 0x6d, 0x6c, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x12, 0x37, 0x0a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x5f, 0x31, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x31, 0x12,
	0x37, 0x0a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x69, 0x6c,
	0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x32, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x15, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x32, 0x12, 0x37, 0x0a, 0x18, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x5f, 0x33, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x33, 0x12, 0x43, 0x0a, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x61, 0x72, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x61, 0x72, 0x79, 0x52, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x12, 0x3d, 0x0a, 0x12, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x52, 0x11, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x61, 0x72, 0x79, 0x12, 0x35, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x11, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x65, 0x70, 0x6f,
	0x63, 0x68, 0x12, 0x22, 0x0a, 0x02, 0x74, 0x77, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x4b,
	0x65, 0x79, 0x52, 0x02, 0x74, 0x77, 0x12, 0x2c, 0x0a, 0x06, 0x74, 0x77, 0x5f, 0x6f, 0x6e, 0x65,
	0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x54, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x4f, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x05, 0x74,
	0x77, 0x4f, 0x6e, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x1d, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x49, 0x64, 0x1a, 0x45, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x8e, 0x02, 0x0a,
	0x04, 0x48, 0x74, 0x6d, 0x6c, 0x12, 0x37, 0x0a, 0x0c, 0x68, 0x74, 0x6d, 0x6c, 0x5f, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x48, 0x74, 0x6d, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x0b, 0x68, 0x74, 0x6d, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x72, 0x6c, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x72, 0x6c, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x03, 0x63, 0x73, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x43, 0x53, 0x53, 0x52, 0x03, 0x63, 0x73, 0x73, 0x12, 0x2b, 0x0a, 0x12, 0x6d, 0x73, 0x67, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x65, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d, 0x73, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50,
	0x65, 0x72, 0x6d, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x32, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x33, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x33, 0x1a, 0x77, 0x0a,
	0x0b, 0x48, 0x74, 0x6d, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x20, 0x0a, 0x0c,
	0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x64, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x64, 0x31, 0x12, 0x24,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x61, 0x77, 0x48, 0x54, 0x4d, 0x4c, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0x20, 0x0a, 0x0c, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f,
	0x69, 0x64, 0x5f, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x49, 0x64, 0x32, 0x1a, 0x1d, 0x0a, 0x07, 0x52, 0x61, 0x77, 0x48, 0x54, 0x4d,
	0x4c, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a, 0x17, 0x0a, 0x03, 0x43, 0x53, 0x53, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x73, 0x73, 0x1a, 0xe4,
	0x03, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61,
	0x72, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e,
	0x74, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x49, 0x6e, 0x74, 0x31, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x32, 0x12, 0x2c, 0x0a, 0x08, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x5f, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x33, 0x52,
	0x07, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x33, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x33, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x33, 0x12, 0x22, 0x0a, 0x0d,
	0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x34, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x34,
	0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x5f,
	0x35, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x49, 0x6e, 0x74, 0x35, 0x12, 0x32, 0x0a, 0x15, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x5f, 0x75, 0x72, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x13, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74,
	0x5f, 0x36, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x49, 0x6e, 0x74, 0x36, 0x1a, 0x24, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f,
	0x33, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x1a, 0xa9, 0x01, 0x0a, 0x0a,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x08, 0x69, 0x6e,
	0x66, 0x6f, 0x5f, 0x61, 0x74, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x69, 0x6e, 0x66, 0x6f, 0x41, 0x74, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12,
	0x46, 0x0a, 0x0e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x6f, 0x74, 0x68, 0x65, 0x72,
	0x49, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0xb6, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x66, 0x6f,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x31, 0x12, 0x25,
	0x0a, 0x0e, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x32, 0x12, 0x35, 0x0a, 0x06, 0x61, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x1a, 0xf1, 0x01, 0x0a, 0x14, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x31, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x6d, 0x65,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x72, 0x0a, 0x1c, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x28, 0x0a, 0x10, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x31, 0x12, 0x28,
	0x0a, 0x10, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x5f, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x32, 0x1a, 0xe7, 0x01, 0x0a, 0x17, 0x4f, 0x74, 0x68,
	0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49,
	0x6e, 0x74, 0x32, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x69,
	0x6e, 0x74, 0x5f, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x33, 0x12, 0x22, 0x0a, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x5f, 0x69, 0x6e, 0x74, 0x5f, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x49, 0x6e, 0x74, 0x34, 0x12, 0x25, 0x0a, 0x0e, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x1a, 0x3d, 0x0a, 0x09, 0x54, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x4b, 0x65, 0x79, 0x12,
	0x30, 0x0a, 0x06, 0x74, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x77, 0x65, 0x6e, 0x74, 0x79,
	0x4b, 0x65, 0x79, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x52, 0x06, 0x74, 0x77, 0x65, 0x6e, 0x74,
	0x79, 0x1a, 0x36, 0x0a, 0x0f, 0x54, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x4b, 0x65, 0x79, 0x4e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x5f, 0x6e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x77, 0x65,
	0x6e, 0x74, 0x79, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x1a, 0x49, 0x0a, 0x0c, 0x54, 0x77, 0x65,
	0x6e, 0x74, 0x79, 0x4f, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x74, 0x77, 0x65,
	0x6e, 0x74, 0x79, 0x5f, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x74, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x5f, 0x6f,
	0x6e, 0x65, 0x5f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x52, 0x09, 0x74, 0x77, 0x65, 0x6e, 0x74,
	0x79, 0x4f, 0x6e, 0x65, 0x1a, 0x3f, 0x0a, 0x11, 0x74, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x5f, 0x6f,
	0x6e, 0x65, 0x5f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x77, 0x65,
	0x6e, 0x74, 0x79, 0x5f, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x77, 0x65, 0x6e, 0x74, 0x79, 0x4f, 0x6e, 0x65, 0x4e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_Message_proto_rawDescOnce sync.Once
	file_Message_proto_rawDescData = file_Message_proto_rawDesc
)

func file_Message_proto_rawDescGZIP() []byte {
	file_Message_proto_rawDescOnce.Do(func() {
		file_Message_proto_rawDescData = protoimpl.X.CompressGZIP(file_Message_proto_rawDescData)
	})
	return file_Message_proto_rawDescData
}

var file_Message_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_Message_proto_goTypes = []interface{}{
	(*Message)(nil),                              // 0: Message
	(*Message_Email)(nil),                        // 1: Message.Email
	(*Message_Html)(nil),                         // 2: Message.Html
	(*Message_HtmlDetails)(nil),                  // 3: Message.HtmlDetails
	(*Message_RawHTML)(nil),                      // 4: Message.RawHTML
	(*Message_CSS)(nil),                          // 5: Message.CSS
	(*Message_SenderSecondary)(nil),              // 6: Message.SenderSecondary
	(*MessageSender_3)(nil),                      // 7: Message.sender_3
	(*Message_Attachment)(nil),                   // 8: Message.Attachment
	(*Message_InfoAttachment)(nil),               // 9: Message.InfoAttachment
	(*Message_InfoAttachmentDetail)(nil),         // 10: Message.InfoAttachmentDetail
	(*Message_InfoInternalAttachmentDetail)(nil), // 11: Message.InfoInternalAttachmentDetail
	(*Message_OtherInternalAttachInfo)(nil),      // 12: Message.OtherInternalAttachInfo
	(*Message_TwentyKey)(nil),                    // 13: Message.TwentyKey
	(*Message_TwentyKeyNested)(nil),              // 14: Message.TwentyKeyNested
	(*Message_TwentyOneKey)(nil),                 // 15: Message.TwentyOneKey
	(*MessageTwentyOneNested)(nil),               // 16: Message.twenty_one_nested
}
var file_Message_proto_depIdxs = []int32{
	1,  // 0: Message.receiver:type_name -> Message.Email
	1,  // 1: Message.cc:type_name -> Message.Email
	1,  // 2: Message.sender:type_name -> Message.Email
	2,  // 3: Message.html:type_name -> Message.Html
	6,  // 4: Message.sender_secondary:type_name -> Message.SenderSecondary
	1,  // 5: Message.receiver_secondary:type_name -> Message.Email
	8,  // 6: Message.attachments:type_name -> Message.Attachment
	13, // 7: Message.tw:type_name -> Message.TwentyKey
	15, // 8: Message.tw_one:type_name -> Message.TwentyOneKey
	3,  // 9: Message.Html.html_details:type_name -> Message.HtmlDetails
	5,  // 10: Message.Html.css:type_name -> Message.CSS
	4,  // 11: Message.HtmlDetails.body:type_name -> Message.RawHTML
	7,  // 12: Message.SenderSecondary.sender_3:type_name -> Message.sender_3
	9,  // 13: Message.Attachment.info_att:type_name -> Message.InfoAttachment
	12, // 14: Message.Attachment.other_int_info:type_name -> Message.OtherInternalAttachInfo
	10, // 15: Message.InfoAttachment.attach:type_name -> Message.InfoAttachmentDetail
	11, // 16: Message.InfoAttachmentDetail.internal_info:type_name -> Message.InfoInternalAttachmentDetail
	14, // 17: Message.TwentyKey.twenty:type_name -> Message.TwentyKeyNested
	16, // 18: Message.TwentyOneKey.twenty_one:type_name -> Message.twenty_one_nested
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_Message_proto_init() }
func file_Message_proto_init() {
	if File_Message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_Html); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_HtmlDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_RawHTML); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_CSS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_SenderSecondary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageSender_3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_Attachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_InfoAttachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_InfoAttachmentDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_InfoInternalAttachmentDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_OtherInternalAttachInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_TwentyKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_TwentyKeyNested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message_TwentyOneKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Message_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageTwentyOneNested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Message_proto_goTypes,
		DependencyIndexes: file_Message_proto_depIdxs,
		MessageInfos:      file_Message_proto_msgTypes,
	}.Build()
	File_Message_proto = out.File
	file_Message_proto_rawDesc = nil
	file_Message_proto_goTypes = nil
	file_Message_proto_depIdxs = nil
}
